# Generated by Django 3.0.5 on 2020-04-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=2083)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=5000)),
                ('question_number', models.CharField(max_length=2000)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Level'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1_answer', models.CharField(max_length=2083)),
                ('option2', models.CharField(blank=True, max_length=2083)),
                ('option3', models.CharField(blank=True, max_length=2083)),
                ('option4', models.CharField(blank=True, max_length=2083)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
