# Generated by Django 3.0.5 on 2020-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200412_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
