# Generated by Django 3.0.5 on 2020-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='team_name',
            field=models.CharField(default='team', max_length=2083),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='team_points',
            field=models.IntegerField(default=0),
        ),
    ]
