# Generated by Django 3.0.5 on 2020-04-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200413_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=2083)),
                ('team_points', models.IntegerField(default=0)),
            ],
        ),
    ]
