# Generated by Django 3.0.5 on 2020-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Answered'), ('RA', 'Right Answer'), ('WA', 'Wrong Answer')], default='NA', max_length=2),
        ),
    ]
