# Generated by Django 3.0.5 on 2020-04-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200413_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='team_name',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='question',
            name='team_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
