# Generated by Django 3.0.5 on 2020-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
