# Generated by Django 3.0.5 on 2020-04-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['marks_alloted']},
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, default='http://via.placeholder.com/72', max_length=2083),
        ),
    ]
