# Generated by Django 3.0.5 on 2020-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200414_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Answered'), ('PQ', 'Passed Question'), ('RA', 'Right Answer'), ('WA', 'Wrong Answer')], default='NA', max_length=2),
        ),
    ]
