# Generated by Django 3.0.5 on 2020-04-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200414_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Level'),
            preserve_default=False,
        ),
    ]
