# Generated by Django 3.0.5 on 2020-04-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_team_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Team'),
            preserve_default=False,
        ),
    ]
