# Generated by Django 3.0.5 on 2020-04-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_question_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='level',
        ),
    ]
