# Generated by Django 3.0.5 on 2020-04-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200416_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='team_points',
        ),
        migrations.AddField(
            model_name='question',
            name='team_choose',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Team'),
        ),
    ]
