# Generated by Django 2.2 on 2020-04-19 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200418_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 4, 19, 7, 54, 44, 624882, tzinfo=utc))),
                ('level', models.IntegerField(blank=True, default=None, null=True)),
                ('team', models.IntegerField(blank=True, default=None, null=True)),
                ('question', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('NA', 'Not Answered'), ('PQ', 'Passed Question'), ('RA', 'Right Answer'), ('WA', 'Wrong Answer')], default='NA', max_length=2)),
                ('marks', models.IntegerField(blank=True, default='None', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AlterField(
            model_name='question',
            name='team_choose',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Team'),
        ),
    ]
