# Generated by Django 2.2 on 2020-04-19 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200419_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 19, 13, 42, 43, 875776, tzinfo=utc)),
        ),
    ]
