# Generated by Django 2.2 on 2020-04-19 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200419_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NA', 'Not Answered'), ('PQ', 'Passed Question'), ('RA', 'Right Answer'), ('WA', 'Wrong Answer')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 19, 15, 59, 43, 885937, tzinfo=utc)),
        ),
    ]
