# Generated by Django 3.0.5 on 2020-04-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200427_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='status',
            new_name='images',
        ),
    ]
