# Generated by Django 3.0.5 on 2020-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200427_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='images',
            field=models.CharField(blank=True, choices=[('https://cms-assets.tutsplus.com/uploads/users/346/posts/31688/image/sportslogos16.jpg', 'Bulls'), ('https://cmkt-image-prd.global.ssl.fastly.net/0.1.0/ps/5942957/300/200/m1/fpnw/wm0/mockuppanda-.jpg?1551077845&s=2efd525056f579874e9030216c4d7c9c', 'Panda'), ('https://designrshub-designrshub.netdna-ssl.com/wp-content/uploads/2019/01/sports-animal-mascot-logo-design-ideas-08.jpg', 'Shark'), ('https://designrshub-designrshub.netdna-ssl.com/wp-content/uploads/2019/01/sports-animal-mascot-logo-design-ideas-13.jpg', 'Deer'), ('https://cdn2.vectorstock.com/i/1000x1000/34/31/wild-wolf-esport-mascot-logo-design-vector-27463431.jpg', 'Wolf'), ('https://designrshub-designrshub.netdna-ssl.com/wp-content/uploads/2019/01/sports-animal-mascot-logo-design-ideas-18.jpg', 'Fox')], default=None, max_length=2000, null=True),
        ),
    ]
