# Generated by Django 2.2 on 2020-05-04 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20200503_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tournament_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tournament'),
        ),
        migrations.AddField(
            model_name='level',
            name='tournament_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tournament'),
        ),
        migrations.AddField(
            model_name='question',
            name='tournament_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tournament'),
        ),
    ]
