# Generated by Django 2.2 on 2020-05-07 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20200504_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
