# Generated by Django 3.0.6 on 2020-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_tournament_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_alloted',
            field=models.IntegerField(default=60),
        ),
    ]
